//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Account Detail
export const GETACCOUNT_REQUEST ='GETACCOUNT_REQUEST';
export const GETACCOUNT_FAILED ='GETACCOUNT_FAILED';
export const GETACCOUNT_RESPONSE ='GETACCOUNT_RESPONSE';

// Personal Information
export const GETPERSONALINFORMATION_REQUEST ='GETPERSONALINFORMATION_REQUEST';
export const GETPERSONALINFORMATION_FAILED ='GETPERSONALINFORMATION_FAILED';
export const GETPERSONALINFORMATION_RESPONSE ='GETPERSONALINFORMATION_RESPONSE';

// User Plan
export const GETUSERPLAN_REQUEST ='GETUSERPLAN_REQUEST';
export const GETUSERPLAN_FAILED ='GETUSERPLAN_FAILED';
export const GETUSERPLAN_RESPONSE ='GETUSERPLAN_RESPONSE';

// Payments
export const GETPAYMENTS_REQUEST ='GETPAYMENTS_REQUEST';
export const GETPAYMENTS_FAILED ='GETPAYMENTS_FAILED';
export const GETPAYMENTS_RESPONSE ='GETPAYMENTS_RESPONSE';

// Profile Image
export const LOADPROFILEIMAGE_REQUEST='LOADPROFILEIMAGE_REQUEST';
export const PROFILEIMAGELOADED_RESPONSE = 'PROFILEIMAGELOADED_RESPONSE';
export const FAILEDLOADINGPROFILEIMAGE_RESPONSE = 'FAILEDLOADINGPROFILEIMAGE_RESPONSE';

//UserProfile
export const LOADUSERPROFILE_REQUEST='LOADUSERPROFILE_REQUEST';
export const USERPROFILELOADED_RESPONSE = 'USERPROFILELOADED_RESPONSE';
export const FAILEDLOADINGUSERPROFILE_RESPONSE = 'FAILEDLOADINGUSERPROFILE_RESPONSE';

//Update Personal Details
export const UPDATEPERSONALDETAIL_REQUEST = 'UPDATEPERSONALDETAIL_REQUEST';
export const UPDATEPERSONALDETAIL_RESPONSE = 'UPDATEPERSONALDETAIL_RESPONSE';
export const UPDATEPERSONALDETAILFAILED_RESPONSE = 'UPDATEPERSONALDETAILFAILED_RESPONSE';

//Update Device Token
export const UPDATEDEVICETOKEN_REQUEST = 'UPDATEDEVICETOKEN_REQUEST';
export const UPDATEDEVICETOKEN_RESPONSE = 'UPDATEDEVICETOKEN_RESPONSE';
export const UPDATEDEVICETOKENFAILED_RESPONSE = 'UPDATEDEVICETOKENFAILED_RESPONSE';

//Change Password
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_RESPONSE = 'CHANGEPASSWORD_RESPONSE';
export const CHANGEPASSWORDFAILED_RESPONSE = 'CHANGEPASSWORDFAILED_RESPONSE';

// Events
export const GETUPCOMINGEVENTS_REQUEST = 'GETUPCOMINGEVENTS_REQUEST';
export const GETUPCOMINGEVENTS_RESPONSE = 'GETUPCOMINGEVENTS_RESPONSE';
export const GETUPCOMINGEVENTSFAILED_RESPONSE = 'GETUPCOMINGEVENTSFAILED_RESPONSE';

export const GETPASTEVENTS_REQUEST = 'GETPASTEVENTS_REQUEST';
export const GETPASTEVENTS_RESPONSE = 'GETPASTEVENTS_RESPONSE';
export const GETPASTEVENTSFAILED_RESPONSE = 'GETPASTEVENTSFAILED_RESPONSE';

export const LOADCUSTOMEREVENTDETAIL_REQUEST='LOADCUSTOMEREVENTDETAIL_REQUEST';
export const CUSTOMEREVENTDETAILLOADED_RESPONSE = 'CUSTOMEREVENTDETAILLOADED_RESPONSE';
export const FAILEDLOADINGCUSTOMEREVENTDETAIL_RESPONSE = 'FAILEDLOADINGCUSTOMEREVENTDETAIL_RESPONSE';

export const LOADEVENTATTENDANCES_REQUEST='LOADEVENTATTENDANCES_REQUEST';
export const EVENTATTENDANCESLOADED_RESPONSE = 'EVENTATTENDANCESLOADED_RESPONSE';
export const FAILEDLOADINGEVENTATTENDANCES_RESPONSE = 'FAILEDLOADINGEVENTATTENDANCES_RESPONSE';

//Send Feedback
export const SENDFEEDBACK_REQUEST = 'SENDFEEDBACK_REQUEST';
export const SENDFEEDBACK_FAILED = 'SENDFEEDBACK_FAILED';
export const SENDFEEDBACK_RESPONSE = 'SENDFEEDBACK_RESPONSE';

//SubscribeNow
export const LOADSUBSCRIBENOW_REQUEST='LOADSUBSCRIBENOW_REQUEST';
export const SUBSCRIBENOWLOADED_RESPONSE = 'SUBSCRIBENOWLOADED_RESPONSE';
export const FAILEDLOADINGSUBSCRIBENOW_RESPONSE = 'FAILEDLOADINGSUBSCRIBENOW_RESPONSE';
