//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Events
export const GETUPCOMINGEVENTS_REQUEST = 'GETUPCOMINGEVENTS_REQUEST';
export const GETUPCOMINGEVENTS_RESPONSE = 'GETUPCOMINGEVENTS_RESPONSE';
export const GETUPCOMINGEVENTSFAILED_RESPONSE = 'GETUPCOMINGEVENTSFAILED_RESPONSE';

export const GETPASTEVENTS_REQUEST = 'GETPASTEVENTS_REQUEST';
export const GETPASTEVENTS_RESPONSE = 'GETPASTEVENTS_RESPONSE';
export const GETPASTEVENTSFAILED_RESPONSE = 'GETPASTEVENTSFAILED_RESPONSE';
