//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// Account Detail
export const GETACCOUNT_REQUEST ='GETACCOUNT_REQUEST';
export const GETACCOUNT_FAILED ='GETACCOUNT_FAILED';
export const GETACCOUNT_RESPONSE ='GETACCOUNT_RESPONSE';

// Personal Information
export const GETPERSONALINFORMATION_REQUEST ='GETPERSONALINFORMATION_REQUEST';
export const GETPERSONALINFORMATION_FAILED ='GETPERSONALINFORMATION_FAILED';
export const GETPERSONALINFORMATION_RESPONSE ='GETPERSONALINFORMATION_RESPONSE';

// User Plan
export const GETUSERPLAN_REQUEST ='GETUSERPLAN_REQUEST';
export const GETUSERPLAN_FAILED ='GETUSERPLAN_FAILED';
export const GETUSERPLAN_RESPONSE ='GETUSERPLAN_RESPONSE';

// Payments
export const GETPAYMENTS_REQUEST ='GETPAYMENTS_REQUEST';
export const GETPAYMENTS_FAILED ='GETPAYMENTS_FAILED';
export const GETPAYMENTS_RESPONSE ='GETPAYMENTS_RESPONSE';

// Healthparameters
export const GETHEALTHPARAMETERS_REQUEST ='GETHEALTHPARAMETERS_REQUEST';
export const GETHEALTHPARAMETERS_FAILED ='GETHEALTHPARAMETERS_FAILED';
export const GETHEALTHPARAMETERS_RESPONSE ='GETHEALTHPARAMETERS_RESPONSE';

// Profile Image
export const LOADPROFILEIMAGE_REQUEST='LOADPROFILEIMAGE_REQUEST';
export const PROFILEIMAGELOADED_RESPONSE = 'PROFILEIMAGELOADED_RESPONSE';
export const FAILEDLOADINGPROFILEIMAGE_RESPONSE = 'FAILEDLOADINGPROFILEIMAGE_RESPONSE';

// UPDATE PROFILE
export const UPDATEUSERPROFILE_REQUEST='UPDATEUSERPROFILE_REQUEST';
export const PROFILEUPDATED_RESPONSE = 'PROFILEUPDATED_RESPONSE';
export const FAILEDUPDATEPROFILE_RESPONSE = 'FAILEDUPDATEPROFILE_RESPONSE';

//UserProfile
export const LOADUSERPROFILE_REQUEST='LOADUSERPROFILE_REQUEST';
export const USERPROFILELOADED_RESPONSE = 'USERPROFILELOADED_RESPONSE';
export const FAILEDLOADINGUSERPROFILE_RESPONSE = 'FAILEDLOADINGUSERPROFILE_RESPONSE';

//Update Device Token
export const UPDATEDEVICETOKEN_REQUEST = 'UPDATEDEVICETOKEN_REQUEST';
export const UPDATEDEVICETOKEN_RESPONSE = 'UPDATEDEVICETOKEN_RESPONSE';
export const UPDATEDEVICETOKENFAILED_RESPONSE = 'UPDATEDEVICETOKENFAILED_RESPONSE';

//Change Password
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_RESPONSE = 'CHANGEPASSWORD_RESPONSE';
export const CHANGEPASSWORDFAILED_RESPONSE = 'CHANGEPASSWORDFAILED_RESPONSE';

// Events
export const GETUPCOMINGEVENTS_REQUEST = 'GETUPCOMINGEVENTS_REQUEST';
export const GETUPCOMINGEVENTS_RESPONSE = 'GETUPCOMINGEVENTS_RESPONSE';
export const GETUPCOMINGEVENTSFAILED_RESPONSE = 'GETUPCOMINGEVENTSFAILED_RESPONSE';

export const GETPASTEVENTS_REQUEST = 'GETPASTEVENTS_REQUEST';
export const GETPASTEVENTS_RESPONSE = 'GETPASTEVENTS_RESPONSE';
export const GETPASTEVENTSFAILED_RESPONSE = 'GETPASTEVENTSFAILED_RESPONSE';

export const LOADCUSTOMEREVENTDETAIL_REQUEST='LOADCUSTOMEREVENTDETAIL_REQUEST';
export const CUSTOMEREVENTDETAILLOADED_RESPONSE = 'CUSTOMEREVENTDETAILLOADED_RESPONSE';
export const FAILEDLOADINGCUSTOMEREVENTDETAIL_RESPONSE = 'FAILEDLOADINGCUSTOMEREVENTDETAIL_RESPONSE';

export const LOADCOORDINATOREVENTDETAIL_REQUEST='LOADCOORDINATOREVENTDETAIL_REQUEST';
export const COORDINATOREVENTDETAILLOADED_RESPONSE = 'COORDINATOREVENTDETAILLOADED_RESPONSE';
export const FAILEDLOADINGCOORDINATOREVENTDETAIL_RESPONSE = 'FAILEDLOADINGCOORDINATOREVENTDETAIL_RESPONSE';

export const LOADEVENTATTENDANCES_REQUEST='LOADEVENTATTENDANCES_REQUEST';
export const EVENTATTENDANCESLOADED_RESPONSE = 'EVENTATTENDANCESLOADED_RESPONSE';
export const FAILEDLOADINGEVENTATTENDANCES_RESPONSE = 'FAILEDLOADINGEVENTATTENDANCES_RESPONSE';

//Send Feedback
export const SENDFEEDBACK_REQUEST = 'SENDFEEDBACK_REQUEST';
export const SENDFEEDBACK_FAILED = 'SENDFEEDBACK_FAILED';
export const SENDFEEDBACK_RESPONSE = 'SENDFEEDBACK_RESPONSE';

//SubscribeNow
export const LOADSUBSCRIBENOW_REQUEST='LOADSUBSCRIBENOW_REQUEST';
export const SUBSCRIBENOWLOADED_RESPONSE = 'SUBSCRIBENOWLOADED_RESPONSE';
export const FAILEDLOADINGSUBSCRIBENOW_RESPONSE = 'FAILEDLOADINGSUBSCRIBENOW_RESPONSE';

// All Healthparameters
export const LOADALLHEALTHPARAMETER_REQUEST ='LOADALLHEALTHPARAMETER_REQUEST';
export const LOADALLHEALTHPARAMETER_FAILED ='LOADALLHEALTHPARAMETER_FAILED';
export const LOADALLHEALTHPARAMETER_RESPONSE ='LOADALLHEALTHPARAMETER_RESPONSE';

export const ADDTOHEALTHPARAMETER_REQUEST='ADDTOHEALTHPARAMETER_REQUEST';
export const ADDTOHEALTHPARAMETER_RESPONSE='ADDTOHEALTHPARAMETER_RESPONSE';
export const ADDTOHEALTHPARAMETERFAILED_RESPONSE='ADDTOHEALTHPARAMETERFAILED_RESPONSE';

// Contracts
export const GETCONTRACTS_REQUEST ='GETCONTRACTS_REQUEST';
export const GETCONTRACTS_FAILED ='GETCONTRACTS_FAILED';
export const GETCONTRACTS_RESPONSE ='GETCONTRACTS_RESPONSE';

export const SIGNCONTRACT_REQUEST='SIGNCONTRACT_REQUEST';
export const SIGNCONTRACT_RESPONSE='SIGNCONTRACT_RESPONSE';
export const SIGNCONTRACTFAILED_RESPONSE='SIGNCONTRACTFAILED_RESPONSE';

//month event
export const GETEVENTSBYMONTH_REQUEST ='GETEVENTSBYMONTH_REQUEST';
export const GETEVENTSBYMONTH_RESPONSE ='GETEVENTSBYMONTH_RESPONSE';
export const GETEVENTSBYMONTHFAILED_RESPONSE = 'GETEVENTSBYMONTHFAILED_RESPONSE';

//date event
export const GETEVENTSBYDATE_REQUEST ='GETEVENTSBYDATE_REQUEST';
export const GETEVENTSBYDATE_RESPONSE ='GETEVENTSBYDATE_RESPONSE';
export const GETEVENTSBYDATEFAILED_RESPONSE ='GETEVENTSBYDATEFAILED_RESPONSE';

//Send ArrivalConfirmation
export const SENDARRIVALCONFIRMATION_REQUEST = 'SENDARRIVALCONFIRMATION_REQUEST';
export const SENDARRIVALCONFIRMATION_FAILED = 'SENDARRIVALCONFIRMATION_FAILED';
export const SENDARRIVALCONFIRMATION_RESPONSE = 'SENDARRIVALCONFIRMATION_RESPONSE';

//Cancel ArrivalConfirmation
export const CANCELARRIVALCONFIRMATION_REQUEST = 'CANCELARRIVALCONFIRMATION_REQUEST';
export const CANCELARRIVALCONFIRMATION_FAILED = 'CANCELARRIVALCONFIRMATION_FAILED';
export const CANCELARRIVALCONFIRMATION_RESPONSE = 'CANCELARRIVALCONFIRMATION_RESPONSE';

// User Role Personal Information
export const GETUSERROLEPERSONALINFORMATION_REQUEST ='GETUSERROLEPERSONALINFORMATION_REQUEST';
export const GETUSERROLEPERSONALINFORMATION_FAILED ='GETUSERROLEPERSONALINFORMATION_FAILED';
export const GETUSERROLEPERSONALINFORMATION_RESPONSE ='GETUSERROLEPERSONALINFORMATION_RESPONSE';

//Check User By Email
export const CHECKUSERBYEMAIL_REQUEST = 'CHECKUSERBYEMAIL_REQUEST';
export const CHECKUSERBYEMAIL_FAILED = 'CHECKUSERBYEMAIL_FAILED';
export const CHECKUSERBYEMAIL_RESPONSE = 'CHECKUSERBYEMAIL_RESPONSE';